### ISSUE TITLE
Error 23

### ISSUE THREAD

**Issue by Karpulza** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#158]
When I try to run the script I get the following error:

Error 23: & does not have a value 
Line: 119

I assume I'm just doing something wrong, but am not a coder, so no idea what it is. Any help would be great, thanks!

**Comment by hsw107** [comment]
@Karpulza Could you please include:

*  A screenshot of the dialog (so I can see the settings you are using)
* Which OS you are on
* Which version of Photoshop you are on (If it's CC please be more specific!)

**Comment by antipalindrome** [comment]
Closing due to lack of information
