### ISSUE TITLE
Auto Run + Unflattened TIFF

### ISSUE THREAD

**Issue by robotasan** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#178]
Hi, not an issue, I'm just not a coder and can't figure out how to modify the code to run on auto and skip the dialog window for batch processing within an action. I have tried to study the other 'Export layers to files' script, but can't figure it out.

Is this a simple addition?

My other less important modification question is, is it possible to have an option to not flatten a TIFF? A PSD will save unflattened with transparency, but not the TIFF.

Thanks for maybe taking these mods into consideration!

**Comment by hsw107** [comment]
Which dialog window are you referring to here?

Also I'm not sure I understand what you mean by having it export not flattened? The script exports individual layers, so by definition there is nothing really to flatten or not to flatten. Or do you mean TIFFs don't export with transparency?

**Comment by ahirtens** [comment]
Hi there... Love the tool. thankyou. But I have also noticed that TIFFs don't export with transparency/alpha channel and seem to be 'flattened with no alpha'.. This would be a great addition. thanks

**Comment by antipalindrome** [comment]
The TIFF transparency is now supported as of 2.5.0. #182 will be used to track the other part of this issue.

**Comment by antipalindrome** [comment]
Auto run is now supported as well, see the latest release and README for more information.
