### ISSUE TITLE
Operation could not be completed 

### ISSUE THREAD

**Issue by MitBoy42** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#180]
PS version: 2020

Windows 10 

I have a file with several sets of folders, and several backrgrounds for each set, as well as one text layer for foreground. So I need to do several exports, in each I only make a certain set of folders and a background visible. 

![image](https://user-images.githubusercontent.com/95524947/144704580-1a18f6eb-8ec8-4162-886c-1c60c06bb037.png)

However, after I do first export successfully, on any other export  I get pop-up "The operation could not be completed" for each picture im trying to export, so none of them get exported. The only way of solving this seems to be closing and opening photoshop, so it's possible to only do one set at a time.

**Comment by hsw107** [comment]
If you rasterize the text layers do you still encounter this issue?

**Comment by antipalindrome** [comment]
Gonna close until I get more info!
