### ISSUE TITLE
Run button 

### ISSUE THREAD

**Issue by plikapisike** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#182]
How can I "activate" / select the Run button, so that I can just press enter and it will run. 
Is there a shortcut or can I create it myself?
I Currently have a shortcut that opens up the script window, I rearly change the settings once I have them set up so I can do everything with just the keyboard and every time I need to run the script I have to use the mouse to click the RUN button, which gets so annoying when you do it 100 times a day.

**Comment by antipalindrome** [comment]
@plikapisike This is now supported as of v2.6.0

Note that this requires a little manual intervention, so please [see the instructions ](https://github.com/antipalindrome/Photoshop-Export-Layers-to-Files-Fast#batch-processing--actions)on how to do this.
