### ISSUE TITLE
Trying to Understand New Silent Running Feature

### ISSUE THREAD

**Issue by JosephMerc** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#183]
Hello! 

I was wondering if there was a description somewhere on how to implement the new Silent running feature; I'm attempting to use the feature in a batch process, and the export dialogue still seems to be appearing. My first instinct is that I'm likely not using the feature as intended, as opposed to this being a bug, so I was just wondering if there was any clarity here? 

Is silent running meant to work with batch processes? Or is it meant to be deployed in another way? 

If it is meant to work in batch processes, I'll follow up with my computer/system/photoshop details, etc...

**Comment by antipalindrome** [comment]
Right now all it does is not show the final confirmation (saving you one click / window) and it doesn't show the progress dialog either.

The initial export dialog still shows. Not showing the initial export dialog seems like a highly requested feature, and I'll use #182  to capture that.

**Comment by antipalindrome** [comment]
@JosephMerc You can now run the script without any dialogs, see the most recent release.
