### ISSUE TITLE
Tiff - Transparency - Request

### ISSUE THREAD

**Issue by Neildlh** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#184]
Hi I found your script which I think is awesome and definitely adds to photoshop. 

Photoshop used to have a feature in their "layers to files export" that allowed you to export tiff images - this has since been removed - 2021 / 2022 versions.

I found your script looking for a solution to this. I need to export tiff's as transparent tiff's. Png is an option - but I want to retain the 300 dpi of a tiff.

Currently my work around is export using your script as psd, then save as tiff. It's a long way around. Definitely
would appreciate a transparent checkbox saving a few minutes in a process.

Well done on the coding of this so far. Your script is brilliant.

**Comment by antipalindrome** [comment]
This is now part of the latest release (2.5.0)!

**Comment by Neildlh** [comment]
Thank you so much. That is a wonderful to here. I hope you have an awesome week!
