### ISSUE TITLE
Progress bar corrupt error

### ISSUE THREAD

**Issue by MDowney64** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#189]
I'm trying to fix the Export to files.  I downloaded the and installed the script but I'm getting this error"Progress bar corrupt" error. I run Windows ultimate 7 and have photoshop 2014. I know it's antique but it's all mine LOL

![ERROR](https://user-images.githubusercontent.com/99101327/152661454-57e68064-8750-4dfc-8738-fd97e1df5ee7.JPG)

**Comment by antipalindrome** [comment]
@MDowney64 Could you show the directory you are running the script from?

Like so:

<img width="485" alt="Screen Shot 2022-02-18 at 16 20 00" src="https://user-images.githubusercontent.com/2524299/154773839-1fd13433-2090-4230-9478-464e91e6e6bd.png">

**Comment by Fredinstein** [comment]
Similar Issue here. I run Windows 10, PS 2020
![image](https://user-images.githubusercontent.com/100692868/156168809-ec4e3714-d73b-4e98-ade0-9e489526d823.png)

Currently running from this directory
![image](https://user-images.githubusercontent.com/100692868/156168964-a08a9931-0039-4f89-a843-4a6e75bd0462.png)

**Comment by righthere** [comment]
Hi! I have the same issue too? Corrupt progress bar error, no matter where is the script, the files are all there.

**Comment by antipalindrome** [comment]
@Fredinstein
You need to have the `.json` file present as well. I can see from your screenshot you only moved the`.jsx` file over. The script will not work without the json.

cc: @righthere
