### ISSUE TITLE
Exporting PNG 24 has no transparency in background layers.

### ISSUE THREAD

**Issue by MhanolloGhames** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#191]
Exporting PNG 24 has no transparency in background layers.
All background layers has color R:233 G:116 B:76 => e9744c

I have Windows 11 updated and Phostoshop 2022 updated.

Please, I need help.

Thank you.

**Comment by MhanolloGhames** [comment]
I solved this problem with update video drivers from Intel and NVidia.
Thank you so much.

**Comment by antipalindrome** [comment]
Glad to hear you were able to get this fixed!
