### ISSUE TITLE
my client will pay for help on a similar photoshop script

### ISSUE THREAD

**Issue by propMaster151** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#192]
Hello,

I would like to know if you are open to freelance work to develop a gui or cli script for my client to use making images out of composite layers in a psd.  It could enhance this project I'd imagine.

Thanks!

Jorge Vicens
mvpsoftware19@gmail.com

**Comment by antipalindrome** [comment]
I'd be curious to know what exactly you mean by composite layers, as I understand them, they are just multiple layers combined (which would already be supported by this script).

But feel free to message me on LinkedIn with more details.
