### ISSUE TITLE
Export Visible Only

### ISSUE THREAD

**Issue by Marcopongo** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#200]
I notice an issue with the Visible Only option
I've a visible layer in a hidden group, but the tool export everything
There're some options that I missed to check?

Thanks

**Comment by antipalindrome** [comment]
Could you share a screenshot of the layers panel and settings you are using so I can make sure to reproduce this effectively?

**Comment by Marcopongo** [comment]
![2022-06-09 10_03_29-Window](https://user-images.githubusercontent.com/105924773/172796855-09fdb0f1-5d3f-46d0-857b-3622c1da668e.png)
this is an example, I want to export only the Group 2 but the script export alle the layer

**Comment by Toggenburger** [comment]
Same problem here.

**Comment by Toggenburger** [comment]
Any news on this? What Info is needed?

**Comment by moegs22** [comment]
I have the same issue as well, but a work around I found is that you turn off every single layer (even hidden groups and their individual layers) and then it exports correctly by selecting 'visible only'. Not exactly the most convenient but it does work!

**Comment by antipalindrome** [comment]
> Any news on this? What Info is needed?

Let me take another look with the screenshot provided above. Unfortunately this is just a script I work on in my spare time at my own expense, so if people are always waiting for me progress is and will be slow. But it is open source so I always welcome outside help to fix bugs or add features.

**Comment by antipalindrome** [comment]
This should be fixed now.
@Marcopongo , @Toggenburger , @moegs22

**Comment by Marcopongo** [comment]
@antipalindrome 
Thanks
I will try it as soon as possible
