### ISSUE TITLE
Duplicating script to have different settings

### ISSUE THREAD

**Issue by dokeng** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#201]
Hey **Hanna**! Thank you so much for this amazing tool! It totally saves lots of time. 

I made some naming settings for an action/batch like version1_documentname. And my other action should take version1_layernames. 
I decided to duplicate script and load it again to Photoshop so i could make another settings but it doesn't work. I can see two different scripts but they sharing same settings somehow. Maybe they have same cache or something like that. 

I guess adding Export Presets can solve my problem. But untill that feature can you give me please a trick to have 2 different scripts with different settings?

Thank you a lot!

**Comment by earwig** [comment]
In the script around line 343, I think you just need to change this settings ID?

```javascript
var USER_SETTINGS_ID = "exportLayersToFilesCustomDefaultSettings";
```

You can probably add a number to the end like `exportLayersToFilesCustomDefaultSettings2`.

**Comment by antipalindrome** [comment]
Thanks for answering this, @earwig ! That's a great workaround :)
