### ISSUE TITLE
Error: General Photoshop error occurred

### ISSUE THREAD

**Issue by FinassaR** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#202]
Every time I run the script i get this issue.  In the screen shot
<img width="1920" alt="Screen Shot 2022-07-13 at 9 07 02 PM" src="https://user-images.githubusercontent.com/54826253/178882535-eb4e0676-5bab-4209-8039-c0aa0c9fdecc.png">

**Comment by antipalindrome** [comment]
Hey there,

So line 2177 is the following:
```
    desc2.putPath(app.charIDToTypeID("In  "), new File(fileName));
```

You could try commenting it out and re-running, or grabbing an older version of the script that may not include this function.

Unfortunately I cannot test against 2020, as I have 2022 photoshop.
