### ISSUE TITLE
Allow suffix/prefix to be visible layer name

### ISSUE THREAD

**Issue by teddywanderlust** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#203]
Hi, is it possible to have a {ln} type of code for one layer that's visible in all exports? What I mean is: I have a layer that I've left visible and so when I export, it shows up on top of all other layers I'm exporting (which is exactly what I want). I'd like to have the name of that single layer appear as suffix in all file names I save. Is that currently possible? If not, could you please implement it? :)

**Comment by antipalindrome** [comment]
This is not possible the way you're wanting it. However you could just fill out the `prefix` field with whatever that layer's name might be, and export it that way, which should give you the desired results.
