### ISSUE TITLE
'All layers' export option does not export all layers

### ISSUE THREAD

**Issue by Lymnah** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#211]
psd has this structure:
A/
├─ SubA/
│  ├─ subA_layer01
│  ├─ subA_layer02
├─ A_layer01
├─ A_layer02
B (same as A)/
C (same as A)/

"All layers" is selected
![image](https://user-images.githubusercontent.com/29931035/201488870-2a53f676-11d1-491d-9a4f-05ecebb0c613.png)

Despite having 1200+ layers, only 33 are exported. Indeed, only the one in visible folders seem to be exported

Photoshop version: 23.5.0
Photoshop-Export-Layers-to-Files-Fast: 824e98c0c6a5aad6a07cea50e65a82cf1038cba4
Windows 11 21H2 (22000.1219)
Same issue on Windows 10

I think the function supposed to push all the layers in the 'layers' variable is not working.

**Comment by Lymnah** [comment]
Update: It only exports visible layers even if the option is unticked:
![image](https://user-images.githubusercontent.com/29931035/202573079-4663e68d-9dfd-401a-a74a-626474d37d78.png)

**Comment by antipalindrome** [comment]
Thanks for reporting this! I'll try to take a look at this soon. Can you let me know if this issue is also happening on [v2.6.0](https://github.com/antipalindrome/Photoshop-Export-Layers-to-Files-Fast/releases/tag/v2.6.0)?

**Comment by antipalindrome** [comment]
@Lymnah Never mind on checking a previous version -- I had time and was able to reproduce and fix this issue. Let me know if you have any issues with [v2.7.1](https://github.com/antipalindrome/Photoshop-Export-Layers-to-Files-Fast/releases/tag/v2.7.1)

**Comment by antipalindrome** [comment]
Also just wanted to note that you left really great info on how to reproduce this, thank you for that!

**Comment by Lymnah** [comment]
@antipalindrome Hi Anti,
It works now, thank you!
